package fdc.repository.dao;

import fdc.repository.model.RsReceive;
import fdc.repository.model.RsReceiveExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface RsReceiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_RECEIVE
     *
     * @mbggenerated Sat Aug 27 13:53:17 CST 2011
     */
    int countByExample(RsReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_RECEIVE
     *
     * @mbggenerated Sat Aug 27 13:53:17 CST 2011
     */
    int deleteByExample(RsReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_RECEIVE
     *
     * @mbggenerated Sat Aug 27 13:53:17 CST 2011
     */
    int deleteByPrimaryKey(String pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_RECEIVE
     *
     * @mbggenerated Sat Aug 27 13:53:17 CST 2011
     */
    int insert(RsReceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_RECEIVE
     *
     * @mbggenerated Sat Aug 27 13:53:17 CST 2011
     */
    int insertSelective(RsReceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_RECEIVE
     *
     * @mbggenerated Sat Aug 27 13:53:17 CST 2011
     */
    List<RsReceive> selectByExample(RsReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_RECEIVE
     *
     * @mbggenerated Sat Aug 27 13:53:17 CST 2011
     */
    RsReceive selectByPrimaryKey(String pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_RECEIVE
     *
     * @mbggenerated Sat Aug 27 13:53:17 CST 2011
     */
    int updateByExampleSelective(@Param("record") RsReceive record, @Param("example") RsReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_RECEIVE
     *
     * @mbggenerated Sat Aug 27 13:53:17 CST 2011
     */
    int updateByExample(@Param("record") RsReceive record, @Param("example") RsReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_RECEIVE
     *
     * @mbggenerated Sat Aug 27 13:53:17 CST 2011
     */
    int updateByPrimaryKeySelective(RsReceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_RECEIVE
     *
     * @mbggenerated Sat Aug 27 13:53:17 CST 2011
     */
    int updateByPrimaryKey(RsReceive record);
}