package fdc.repository.model;

import java.math.BigDecimal;
import java.util.Date;

public class BiAccountDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACCOUNT_DETAIL.PK_ID
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    private String pkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACCOUNT_DETAIL.ACCOUNT_CODE
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    private String accountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACCOUNT_DETAIL.TO_ACCOUNT_CODE
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    private String toAccountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACCOUNT_DETAIL.INOUT_FLAG
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    private String inoutFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACCOUNT_DETAIL.TRADE_AMOUNT
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    private BigDecimal tradeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACCOUNT_DETAIL.SERIAL
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    private Long serial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACCOUNT_DETAIL.BANK_SERIAL
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    private String bankSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACCOUNT_DETAIL.TRADE_DATE
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    private Date tradeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACCOUNT_DETAIL.TRADE_TIME
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    private String tradeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACCOUNT_DETAIL.TRADE_TYPE
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    private String tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACCOUNT_DETAIL.PURPOSE
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    private String purpose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACCOUNT_DETAIL.REMARK
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACCOUNT_DETAIL.ECHECK_FLAG
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    private String echeckFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACCOUNT_DETAIL.CHANGE_FLAG
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    private String changeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACCOUNT_DETAIL.DELETED_FLAG
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    private String deletedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACCOUNT_DETAIL.ORIGIN_FLAG
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    private String originFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACCOUNT_DETAIL.CREATED_BY
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACCOUNT_DETAIL.CREATED_DATE
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACCOUNT_DETAIL.LAST_UPD_BY
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    private Long lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACCOUNT_DETAIL.LAST_UPD_DATE
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    private Date lastUpdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACCOUNT_DETAIL.MODIFICATION_NUM
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    private Integer modificationNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.PK_ID
     *
     * @return the value of BRZFDC.BI_ACCOUNT_DETAIL.PK_ID
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public String getPkId() {
        return pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.PK_ID
     *
     * @param pkId the value for BRZFDC.BI_ACCOUNT_DETAIL.PK_ID
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public void setPkId(String pkId) {
        this.pkId = pkId == null ? null : pkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.ACCOUNT_CODE
     *
     * @return the value of BRZFDC.BI_ACCOUNT_DETAIL.ACCOUNT_CODE
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.ACCOUNT_CODE
     *
     * @param accountCode the value for BRZFDC.BI_ACCOUNT_DETAIL.ACCOUNT_CODE
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode == null ? null : accountCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.TO_ACCOUNT_CODE
     *
     * @return the value of BRZFDC.BI_ACCOUNT_DETAIL.TO_ACCOUNT_CODE
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public String getToAccountCode() {
        return toAccountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.TO_ACCOUNT_CODE
     *
     * @param toAccountCode the value for BRZFDC.BI_ACCOUNT_DETAIL.TO_ACCOUNT_CODE
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public void setToAccountCode(String toAccountCode) {
        this.toAccountCode = toAccountCode == null ? null : toAccountCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.INOUT_FLAG
     *
     * @return the value of BRZFDC.BI_ACCOUNT_DETAIL.INOUT_FLAG
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public String getInoutFlag() {
        return inoutFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.INOUT_FLAG
     *
     * @param inoutFlag the value for BRZFDC.BI_ACCOUNT_DETAIL.INOUT_FLAG
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public void setInoutFlag(String inoutFlag) {
        this.inoutFlag = inoutFlag == null ? null : inoutFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.TRADE_AMOUNT
     *
     * @return the value of BRZFDC.BI_ACCOUNT_DETAIL.TRADE_AMOUNT
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public BigDecimal getTradeAmount() {
        return tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.TRADE_AMOUNT
     *
     * @param tradeAmount the value for BRZFDC.BI_ACCOUNT_DETAIL.TRADE_AMOUNT
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public void setTradeAmount(BigDecimal tradeAmount) {
        this.tradeAmount = tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.SERIAL
     *
     * @return the value of BRZFDC.BI_ACCOUNT_DETAIL.SERIAL
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public Long getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.SERIAL
     *
     * @param serial the value for BRZFDC.BI_ACCOUNT_DETAIL.SERIAL
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public void setSerial(Long serial) {
        this.serial = serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.BANK_SERIAL
     *
     * @return the value of BRZFDC.BI_ACCOUNT_DETAIL.BANK_SERIAL
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public String getBankSerial() {
        return bankSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.BANK_SERIAL
     *
     * @param bankSerial the value for BRZFDC.BI_ACCOUNT_DETAIL.BANK_SERIAL
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public void setBankSerial(String bankSerial) {
        this.bankSerial = bankSerial == null ? null : bankSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.TRADE_DATE
     *
     * @return the value of BRZFDC.BI_ACCOUNT_DETAIL.TRADE_DATE
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public Date getTradeDate() {
        return tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.TRADE_DATE
     *
     * @param tradeDate the value for BRZFDC.BI_ACCOUNT_DETAIL.TRADE_DATE
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public void setTradeDate(Date tradeDate) {
        this.tradeDate = tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.TRADE_TIME
     *
     * @return the value of BRZFDC.BI_ACCOUNT_DETAIL.TRADE_TIME
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public String getTradeTime() {
        return tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.TRADE_TIME
     *
     * @param tradeTime the value for BRZFDC.BI_ACCOUNT_DETAIL.TRADE_TIME
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public void setTradeTime(String tradeTime) {
        this.tradeTime = tradeTime == null ? null : tradeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.TRADE_TYPE
     *
     * @return the value of BRZFDC.BI_ACCOUNT_DETAIL.TRADE_TYPE
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.TRADE_TYPE
     *
     * @param tradeType the value for BRZFDC.BI_ACCOUNT_DETAIL.TRADE_TYPE
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.PURPOSE
     *
     * @return the value of BRZFDC.BI_ACCOUNT_DETAIL.PURPOSE
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.PURPOSE
     *
     * @param purpose the value for BRZFDC.BI_ACCOUNT_DETAIL.PURPOSE
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public void setPurpose(String purpose) {
        this.purpose = purpose == null ? null : purpose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.REMARK
     *
     * @return the value of BRZFDC.BI_ACCOUNT_DETAIL.REMARK
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.REMARK
     *
     * @param remark the value for BRZFDC.BI_ACCOUNT_DETAIL.REMARK
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.ECHECK_FLAG
     *
     * @return the value of BRZFDC.BI_ACCOUNT_DETAIL.ECHECK_FLAG
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public String getEcheckFlag() {
        return echeckFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.ECHECK_FLAG
     *
     * @param echeckFlag the value for BRZFDC.BI_ACCOUNT_DETAIL.ECHECK_FLAG
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public void setEcheckFlag(String echeckFlag) {
        this.echeckFlag = echeckFlag == null ? null : echeckFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.CHANGE_FLAG
     *
     * @return the value of BRZFDC.BI_ACCOUNT_DETAIL.CHANGE_FLAG
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public String getChangeFlag() {
        return changeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.CHANGE_FLAG
     *
     * @param changeFlag the value for BRZFDC.BI_ACCOUNT_DETAIL.CHANGE_FLAG
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public void setChangeFlag(String changeFlag) {
        this.changeFlag = changeFlag == null ? null : changeFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.DELETED_FLAG
     *
     * @return the value of BRZFDC.BI_ACCOUNT_DETAIL.DELETED_FLAG
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public String getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.DELETED_FLAG
     *
     * @param deletedFlag the value for BRZFDC.BI_ACCOUNT_DETAIL.DELETED_FLAG
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public void setDeletedFlag(String deletedFlag) {
        this.deletedFlag = deletedFlag == null ? null : deletedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.ORIGIN_FLAG
     *
     * @return the value of BRZFDC.BI_ACCOUNT_DETAIL.ORIGIN_FLAG
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public String getOriginFlag() {
        return originFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.ORIGIN_FLAG
     *
     * @param originFlag the value for BRZFDC.BI_ACCOUNT_DETAIL.ORIGIN_FLAG
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public void setOriginFlag(String originFlag) {
        this.originFlag = originFlag == null ? null : originFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.CREATED_BY
     *
     * @return the value of BRZFDC.BI_ACCOUNT_DETAIL.CREATED_BY
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.CREATED_BY
     *
     * @param createdBy the value for BRZFDC.BI_ACCOUNT_DETAIL.CREATED_BY
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.CREATED_DATE
     *
     * @return the value of BRZFDC.BI_ACCOUNT_DETAIL.CREATED_DATE
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.CREATED_DATE
     *
     * @param createdDate the value for BRZFDC.BI_ACCOUNT_DETAIL.CREATED_DATE
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.LAST_UPD_BY
     *
     * @return the value of BRZFDC.BI_ACCOUNT_DETAIL.LAST_UPD_BY
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public Long getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.LAST_UPD_BY
     *
     * @param lastUpdBy the value for BRZFDC.BI_ACCOUNT_DETAIL.LAST_UPD_BY
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public void setLastUpdBy(Long lastUpdBy) {
        this.lastUpdBy = lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.LAST_UPD_DATE
     *
     * @return the value of BRZFDC.BI_ACCOUNT_DETAIL.LAST_UPD_DATE
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public Date getLastUpdDate() {
        return lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.LAST_UPD_DATE
     *
     * @param lastUpdDate the value for BRZFDC.BI_ACCOUNT_DETAIL.LAST_UPD_DATE
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public void setLastUpdDate(Date lastUpdDate) {
        this.lastUpdDate = lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.MODIFICATION_NUM
     *
     * @return the value of BRZFDC.BI_ACCOUNT_DETAIL.MODIFICATION_NUM
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public Integer getModificationNum() {
        return modificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACCOUNT_DETAIL.MODIFICATION_NUM
     *
     * @param modificationNum the value for BRZFDC.BI_ACCOUNT_DETAIL.MODIFICATION_NUM
     *
     * @mbggenerated Fri Aug 26 14:17:47 CST 2011
     */
    public void setModificationNum(Integer modificationNum) {
        this.modificationNum = modificationNum;
    }
}